/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.sampleapp;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int back_to_picture_btn=0x7f020000;
        public static final int buttons_back=0x7f020001;
        public static final int cancel=0x7f020002;
        public static final int capture_video=0x7f020003;
        public static final int forward_btn=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int photo_capture=0x7f020006;
        public static final int photo_library=0x7f020007;
        public static final int preview_back=0x7f020008;
        public static final int video_capture_btn=0x7f020009;
    }
    public static final class id {
        public static final int button_album=0x7f060006;
        public static final int button_cancel=0x7f060000;
        public static final int button_capture=0x7f060004;
        public static final int button_preview=0x7f060001;
        public static final int button_video=0x7f060007;
        public static final int camera_preview=0x7f060005;
        public static final int linearLayout1=0x7f060003;
        public static final int progressBar1=0x7f060002;
    }
    public static final class layout {
        public static final int audiocapture=0x7f030000;
        public static final int foregroundcameraplugin=0x7f030001;
        public static final int videocapture=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
